'use strict';

let btnStart =                  document.getElementById('start');
let salaryAmount =              document.querySelector('.salary-amount');
let incomeTitle =               document.querySelector('.income-title');
let incomeAmount =              document.querySelector('.income-amount');
let additionalIncomeItems =     document.querySelectorAll('.additional_income-item');
let additionalIncomeItem1 =     additionalIncomeItems[0];
let additionalIncomeItem2 =     additionalIncomeItems[1];
let arrPlus =                   document.querySelectorAll('.btn_plus');
let incomePlus =                arrPlus[0];
let expensePlus =               arrPlus[1];
let additionalIncomeTitle =     document.querySelector('.additional_income-title');
let additionalIncomeItem =      document.querySelectorAll('.additional_income-item');
let expensesTitle =             document.querySelector('.expenses-title');
let expensesAmount =            document.querySelector('.expenses-amount');
let additionalExpensesItemd =   document.querySelector('.additional_expenses-item');
let depositCheck =              document.querySelector('#deposit-check');
let depositAmount =             document.querySelector('.deposit-amount');
let depositPercent =            document.querySelector('.deposit-percent');
let targetAmount =              document.querySelector('.target-amount');
let periodSelect =              document.querySelector('.period-select');
let budgetMonthValue =          document.querySelector('.budget_month-value');
let budgetDayValue =            document.querySelector('.budget_day-value');
let expensesMonthValue =        document.querySelector('.expenses_month-value');
let additionalIncomeValue =     document.querySelector('.additional_income-value');
let additionalExpensesValue =   document.querySelector('.additional_expenses-value');
let incomePeriodValue =         document.querySelector('.income_period-value');
let targetMonthValue =          document.querySelector('.target_month-value');

console.log(btnStart, salaryAmount, incomeTitle, incomeAmount, additionalIncomeItems, additionalIncomeItem1, additionalIncomeItem1, arrPlus, incomePlus, expensePlus, additionalIncomeTitle, additionalIncomeItem, expensesTitle, expensesAmount, additionalExpensesItemd, depositCheck, depositAmount, depositPercent, targetAmount, periodSelect, budgetMonthValue, budgetDayValue, expensesMonthValue, additionalIncomeValue, additionalExpensesValue,incomePeriodValue, targetMonthValue);